[package]
name = "cextractor"
version = "0.1.0"
authors = ["Adam Ruman <469068@muni.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
